import Navbar from "./components/Navbar";
import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import { connectMongodb } from "./services";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const mongoConnection= await connectMongodb();
 
  if(mongoConnection && mongoConnection.connection && mongoConnection.connection.readyState===1){
    console.log('Mongodb connection has been established')
  }
  else {
    console.log('Mongodb connection has failed')
  }
  return (
    <html lang="en">
      <body
      >
        <AuthProvider>
            <Navbar></Navbar>
            {children}
        </AuthProvider>
     
      </body>
    </html>
  );
}
